# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export Hawkes
NULL

#' @export ExpHawkes
NULL

gammaf1 <- function(xi, binSize, param, maxIndex) {
    .Call('discreteHawkes_gammaf1', PACKAGE = 'discreteHawkes', xi, binSize, param, maxIndex)
}

